Resources:
  SSMDocument:
    Type: 'AWS::SSM::Document'
    Properties:
      Content:
        schemaVersion: '2.2'
        description: Creates a local user
        parameters:
          usernames:
            description: (Required) Enter list of users to create user1,user2,user3.
            type: StringList
            minItems: 1
          # username:
          #   description: (Required) Username to create.
          #   type: String
          #   default: ''
          # ssmparameter:
          #   description: (Required) SSM parameter that stores the password of the user.
          #   type: String
          #   default: ''
          executionTimeout:
            description: >-
              (Optional) The time in seconds for a command to complete before it
              is considered to have failed. Default is 3600 (1 hour). Maximum is
              28800 (8 hours).
            type: String
            default: '3600'
            allowedPattern: >-
              ([1-9][0-9]{0,3})|(1[0-9]{1,4})|(2[0-7][0-9]{1,3})|(28[0-7][0-9]{1,2})|(28800)
        mainSteps:
          - precondition:
              StringEquals:
                - platformType
                - Linux
            action: 'aws:runShellScript'
            name: runShellScript
            inputs:
              runCommand:
                - |
                  $users="{{usernames}}"

                  for user in ${users[@]}; do
                    echo $user
                  done
              timeoutSeconds: '{{ executionTimeout }}'
      DocumentFormat: YAML
      DocumentType: Command
      Name: CreateUserSSM
